import Head from "next/head";
import { type PropsWithChildren } from "react";
import Header from "./header";

export default function Layout({ children }: PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Intermittent Fasting Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative h-screen overflow-hidden bg-gray-100 dark:bg-gray-800">
        <div className="flex items-start justify-between">
          <div className="flex w-full flex-col md:space-y-4">
            <Header />
            <div className="h-screen overflow-auto px-4 pb-24 md:px-6">
              {children}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
